### ISSUE TITLE
get rows select

### ISSUE THREAD

**Issue by vinySan** [TBertuzzi/Xamarin.Forms.MultiSelectListView#3]
Can I create a list of objects in this selection?
For the moment I do it but when I unselect a row a new record is created
`List<string> Prueba = new List<string>();
        public MultiSelectObservableCollection<CanalDAO> Modelos { get; }

        public ICommand DisplayNameCommand => new Command<CanalDAO>(async canal =>
        {
           
           Prueba.Add(canal.DESCRIPCION);

           
                  
        });`
include my code.

**Comment by TBertuzzi** [comment]
I did not understand your problem.
