### ISSUE TITLE
Initial selected items

### ISSUE THREAD

**Issue by nakulashok** [TBertuzzi/Xamarin.Forms.MultiSelectListView#4]
How can i make a set of items as selected when the view is generated.

**Comment by TBertuzzi** [comment]
It is only possible after adding in the MultiSelectObservableCollection, after adding an item to change its property to IsSelected = true;

Example :

```csharp
Users = new MultiSelectObservableCollection<User>();

            User user = new User();
            user.Name = "Bertuzzi";
            Users.Add(user);
```

**Comment by nakulashok** [comment]
> It is only possible after adding in the MultiSelectObservableCollection, after adding an item to change its property to IsSelected = true;
> 
> Example :
> 
> ```cs
> Users = new MultiSelectObservableCollection<User>();
> 
>             User user = new User();
>             user.Name = "Bertuzzi";
>             Users.Add(user);
>             Users[0].IsSelected = true;
> ```

**Comment by nakulashok** [comment]
Thanks,
I will look into it

**Comment by nakulashok** [comment]
Yea it worked. Thanks
