### ISSUE TITLE
Problem in showing selected item 

### ISSUE THREAD

**Issue by ronakshethia** [TBertuzzi/Xamarin.Forms.MultiSelectListView#7]
can you please help me how can i show my selected items back on page load,
i have a id property which i save when user selects the item and i store that value on app so that if user comes back on same page he can see the selected values.

where as i am only able to set the selected item on passing the index so could you please suggest me something

**Comment by TBertuzzi** [comment]
It is only possible after adding in the MultiSelectObservableCollection, after adding an item to change its property to IsSelected = true;

Example :

```csharp
Users = new MultiSelectObservableCollection<User>();

            User user = new User();
            user.Name = "Bertuzzi";
            Users.Add(user);
            Users[0].IsSelected = true;
```
